### ISSUE TITLE
Can we specify the computer name manually?

### ISSUE THREAD

**Issue by c3rberus** [mtniehaus/RenameComputer#3]
We have a strict requirement to name our computers a certain format and none of this is derived from data available on the machine (its not serial based where we can just look inside the BIOS using WMIC).

Is there a way to prompt for a computer name and use that?

**Comment by mtniehaus** [comment]
That would be a lot more work.  It's impossible to prompt from a Win32 app, so the prompting would need to be once the user signs in.  But if that saved the name somewhere a script could find it, it could pick it up and process it with a scheduled task.
