### ISSUE TITLE
Script might hang due to Netbios / 15 char

### ISSUE THREAD

**Issue by rrseeley** [mtniehaus/RenameComputer#5]
I changed the rename portion of the script to suit my needs and ran into an issue where the script would spin indefinitely on 'Installing'  .. turns out some of my computer names exceeded the 15 char netbios limit and was throwing up a confirmation box. 

To address this, add -Force to the end of the Rename-Computer command: 

Rename-Computer -NewName $newName -Force

**Comment by mtniehaus** [comment]
I added that in the new version, so it's there by default :-)
