### ISSUE TITLE
Get-ComputerInfo BiosSerialNumber is actually BiosSeralNumber

### ISSUE THREAD

**Issue by Harshmage** [mtniehaus/RenameComputer#7]
https://github.com/mtniehaus/RenameComputer/blob/83460aa26c89b8c6c64d04d1bf94b736087762cc/RenameComputer/RenameComputer.ps1#L118

Simple fix, but the actual property tag for the BIOS Serial Number in Get-ComputerInfo is actually BiosSeralNumber, at least on Windows 11.

**Comment by jamesvincent** [comment]
I was about to say, who fat fingered this one?! #typo.

**Comment by Harshmage** [comment]
@jamesvincent It actually looks to be an issue in Powershell 5!  Powershell 7 has the proper naming "BiosSer**i**alNumber", but since PS 7 isn't the standard in the OS yet, this will probably still have issues for newly built systems.

**Comment by mtniehaus** [comment]
I checked in a fix for that to handle either property name.
