### ISSUE TITLE
Would/Could you not run this as a Remediation?

### ISSUE THREAD

**Issue by jamesvincent** [mtniehaus/RenameComputer#8]
Couldn't the .ps1 just be run as a remediation? Give or take a bit of detection tweaking -- I mean, the logic is already in there really... Or am I missing something?

I suspect the creation of this solution pre-dates remediation...??

...Or, is it an App so that it can run during OOBE? (and therefore if I'm happy to run post OOBE, I can proceed as a script/remediation, with the relevant parts of the .ps1...)

**Comment by mtniehaus** [comment]
It could, but then there will always be a delay before it renames.  With the Win32 app (which just bundles the script into a .intunewin file), if the device is on the corporate network it will work right away and reboot at the end of ESP.  With a remediation script, it would run post-ESP and need to do a more managed reboot.

But overall it just depends on your requirements.
